# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  HardCore Configuration File
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Debug:
  Enabled: true
# Broadcasts all debug messages to chat (spammy!)
  BroadcastChatEnabled: false
