# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  HardCore Configuration File
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Debug:
  Enabled: true
# Broadcasts all debug messages to chat (spammy!)
  BroadcastChatEnabled: false

Options:
  DefaultNumberOfLives: 5
  DeadPrefix: "§c§l[§4DEAD§c§l]"
