# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  HardCore Configuration File
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Debug:
  Enabled: true
# Broadcasts all debug messages to chat (spammy!)
  BroadcastChatEnabled: false

Options:
  DefaultNumberOfLives: 5
# How long to spend in Limbo, ie: 1d 7h 12m 32s
  DefaultTimeInLimbo: 2m
  DeadPrefix: "§c§l[§4DEAD§c§l]"
